version: '3.7'
services:
  redis:
    image: "redis:7.2.5"
    container_name: "redis"
    env_file:
      - .env
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - redis-data:/data
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # frontend:
  #   container_name: "frontend"
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   tty: true
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - db
  #     - redis
  #   restart: on-failure

volumes:
  redis-data:
    