services:
  redis:
    image: "redis:7.2.5"
    container_name: "redis"
    env_file:
      - .env
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - redis-data:/data
    networks:
    - network
    
  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
    - network
  
  backend:
    container_name: "backend"
    image: rosvalde/api:latest
    tty: true
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    restart: on-failure
    networks:
      - network

  # frontend:
  #   container_name: "frontend"
  #   image: rosvalde/frontend:latest
  #   tty: true
  #   env_file:
  #     - .env
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - backend
  #   restart: on-failure
  #   networks:
  #     - network

volumes:
  redis-data:
  db-data:

networks:
  network:
    driver: bridge
    