name: web project CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: lint, format
        run: npm run lint && npm run format

      - name: Install dependencies
        run: npm install 

      # - name: Run tests
      #   run: npm run test

      - name: Build project
        run: npm run build
